### PR TITLE
log header and background

### PR DESCRIPTION
**Pull request by debdeep12**
Covers:
1. Pill background not covering text : https://app.asana.com/0/1202175785976708/1203451635643843
2. Logs header is transparent: https://app.asana.com/0/1202175785976708/1203451635643848

### CODE REVIEW

**Review by acolver — APPROVED** [review]

**Comment by acolver** [comment]
@guptamukul-google Did you want him to merge to `staging` or point directly to `GoogleCloudPlatform/rad-lab:staging`?

**Comment by guptamukul-google** [comment]
@debdeep12 Please point this PR directly to `GoogleCloudPlatform/rad-lab:staging`

**Review by guptamukul-google — CHANGES_REQUESTED** [review]
Please point this PR directly to `GoogleCloudPlatform/rad-lab:staging` instead of `GPS-Demos/rad-lab:staging`

**Comment by debdeep12** [comment]
Need to reopen

**Comment by debdeep12** [comment]
Need to open in public repo

**Pull request closed without merging**
